In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from vega_datasets import data

In [2]:
# loading data
corona = pd.read_csv('~/Desktop/Code n Stuff/pghcoffee.csv')
columnsList = list(corona.columns)

# preparing data
corona_spring = corona.sort_values(['State', 'County Name'])
corona_spring.reset_index(drop=True, inplace=True)
corona_spring

,countyFIPS,County Name,State,stateFIPS,1/22/2020,1/23/2020,1/24/2020,1/25/2020,1/26/2020,1/27/2020,...,4/2/2020,4/3/2020,4/4/2020,4/5/2020,4/6/2020,4/7/2020,4/8/2020,4/9/2020,4/10/2020,4/11/2020
0,2013,Aleutians East Borough,AK,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2016,Aleutians West Census Area,AK,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2050,Bethel Census Area,AK,2,0,0,0,0,0,0,...,0,0,0,0,0,1,1,1,1,1
3,2060,Bristol Bay Borough,AK,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2110,City and Borough of Juneau,AK,2,0,0,0,0,0,0,...,10,11,12,14,14,14,14,14,15,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3190,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,3,3,4,5,5,6,6,6,7,7
3191,56039,Teton County,WY,56,0,0,0,0,0,0,...,29,32,36,39,40,44,45,50,53,53
3192,56041,Uinta County,WY,56,0,0,0,0,0,0,...,1,1,2,2,3,3,3,4,4,4
3193,56043,Washakie County,WY,56,0,0,0,0,0,0,...,2,2,2,4,4,5,5,5,5,5
3194,56045,Weston County,WY,56,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [42]:
# separate data into 51 separate datasets
def filterByState():
    states = list(corona_spring.State.unique())
    numOfCounties = len(corona_spring)
    byStates = []

    for state in states:
        corona_byState = corona_spring[corona_spring['State'] == state]
        byStates.append(corona_byState)
    return byStates

# transpose the 51 datasets 
def transposeByDate():
    byDates = []
    
    corona_byStates = filterByState()
    for item in corona_byStates:
        byDate = item.transpose()
        byDate_Mar1 = byDate.loc['3/10/2020':,]
        byDates.append(byDate)
    return byDates

corona_byDates = transposeByDate()

# plotting all 51 datasets
print(type(corona_byDates[0]))
graph = corona_byDates[0].plot(kind='line')
graph.show
#for item in corona_byDates:
    #print(item)
    #graph = item.plot(kind = 'line', legend=None)
    #graph.show()

<class 'pandas.core.frame.DataFrame'>

TypeError: no numeric data to plot

In [31]:
len(corona_byStates)

51

In [3]:
# aggregating counties by states
casesByState = corona_spring.groupby('State')[columnsList[4:]].sum()
casesByState

,1/22/2020,1/23/2020,1/24/2020,1/25/2020,1/26/2020,1/27/2020,1/28/2020,1/29/2020,1/30/2020,1/31/2020,...,4/2/2020,4/3/2020,4/4/2020,4/5/2020,4/6/2020,4/7/2020,4/8/2020,4/9/2020,4/10/2020,4/11/2020
State,,,,,,,,,,,,,,,,,,,,,
AK,0,0,0,0,0,0,0,0,0,0,...,147,157,171,185,191,213,226,236,247,258
AL,0,0,0,0,0,0,0,0,0,0,...,1270,1534,1632,1840,2003,2197,2499,2838,3007,3262
AR,0,0,0,0,0,4,0,0,0,0,...,678,732,740,853,927,997,1077,1146,1202,1228
AZ,0,0,0,0,1,1,1,1,1,1,...,1596,1769,2018,2269,2456,2575,2726,3018,3111,3393
CA,0,0,0,0,2,2,2,2,2,3,...,11170,12563,13886,15204,16356,17538,19043,20184,21376,22413
CO,0,0,0,0,0,0,0,0,0,0,...,3724,4173,4565,4950,5172,5429,5655,6098,6322,6638
CT,0,0,0,0,0,0,0,0,0,0,...,3824,4915,5276,5675,6906,7781,8781,9784,10538,11510
DC,0,0,0,0,0,0,0,0,0,0,...,653,757,902,998,1097,1211,1440,1523,1660,1778
DE,0,0,0,0,0,0,0,0,0,0,...,393,450,593,673,783,928,1116,1209,1326,1479
FL,0,0,0,0,0,0,0,0,0,0,...,9008,10268,11544,12350,13629,14747,15698,16826,17968,18986
GA,0,0,0,0,0,0,0,0,0,0,...,5440,5960,6374,6731,7554,9156,10204,10885,11856,12261
HI,0,0,0,0,0,0,0,0,0,0,...,285,319,351,371,387,410,435,442,465,486
IA,0,0,0,0,0,0,0,0,0,0,...,614,699,785,868,945,1048,1145,1270,1388,1510
ID,0,0,0,0,0,0,0,0,0,0,...,889,1011,1076,1100,1169,1210,1232,1353,1396,1407
IL,0,0,1,1,1,1,1,1,1,2,...,7678,8871,10357,11254,12259,13553,15078,16422,17884,19180
IN,0,0,0,0,0,0,0,0,0,0,...,3038,3436,3948,4409,4942,5507,5943,6351,6907,7435
KS,0,0,0,0,0,0,0,0,0,0,...,550,620,698,747,845,900,1045,1106,1165,1268
KY,0,0,0,0,0,0,0,0,0,0,...,717,778,874,977,1088,1144,1346,1520,1699,1840
LA,0,0,0,0,0,0,0,0,0,0,...,9094,10169,12493,13010,14866,16284,17030,18283,19252,20014
MA,0,0,0,0,0,0,0,0,0,0,...,8966,10402,11736,12500,13837,15200,16790,18941,20974,22860
MD,0,0,0,0,0,0,0,0,0,0,...,2331,2758,3125,3609,4045,4371,5529,6185,6968,7694
ME,0,0,0,0,0,0,0,0,0,0,...,376,432,456,470,499,519,537,560,586,616
MI,0,0,0,0,0,0,0,0,0,0,...,10789,12739,14222,15713,17218,18969,20345,21503,22781,23993
MN,0,0,0,0,0,0,0,0,0,0,...,742,788,863,928,980,1069,1155,1245,1245,1245
MO,0,0,0,0,0,0,0,0,0,0,...,1833,2111,2285,2369,2723,3037,3327,3539,3789,4024
MS,0,0,0,0,0,0,0,0,0,0,...,1178,1460,1566,1748,1848,1915,2003,2258,2465,2642
MT,0,0,0,0,0,0,0,0,0,0,...,241,262,281,297,319,319,332,332,332,332
NC,0,0,0,0,0,0,0,0,0,0,...,1855,2093,2402,2585,2870,3221,3426,3654,3909,4313
ND,0,0,0,0,0,0,0,0,0,0,...,159,173,186,207,225,237,251,269,278,293
NE,0,0,0,0,0,0,0,0,0,0,...,254,284,318,354,402,478,523,577,647,704
NH,0,0,0,0,0,0,0,0,0,0,...,479,540,620,669,715,747,788,819,885,928
NJ,0,0,0,0,0,0,0,0,0,0,...,25590,29895,34997,37505,41091,44416,47437,51393,54588,58151
NM,0,0,0,0,0,0,0,0,0,0,...,403,494,545,626,688,796,865,989,1090,1174
NV,0,0,0,0,0,0,0,0,0,0,...,1458,1551,1752,1836,1953,2098,2318,2456,2624,2624
NY,0,0,0,0,0,0,0,0,0,0,...,90390,103652,113892,122178,130830,138988,149476,159937,170512,180533
OH,0,0,0,0,0,0,0,0,0,0,...,2902,3312,3738,4041,4442,4782,5148,5512,5878,6250
OK,0,0,0,0,0,0,0,0,0,0,...,877,987,1157,1251,1325,1469,1522,1681,1790,1868
OR,0,0,0,0,0,0,0,0,0,0,...,825,898,999,1067,1132,1181,1239,1321,1371,1447
PA,0,0,0,0,0,0,0,0,0,0,...,7016,8420,10016,11496,12973,14559,16239,18228,19978,21655
RI,0,0,0,0,0,0,0,0,0,0,...,651,705,806,922,1082,1229,1439,1712,2015,2349
SC,0,0,0,0,0,0,0,0,0,0,...,1553,1699,1913,2048,2230,2417,2552,2792,3065,3065
SD,0,0,0,0,0,0,0,0,0,0,...,165,187,212,240,285,320,393,447,534,626
TN,0,0,0,0,0,0,0,0,0,0,...,2844,3066,3320,3632,3801,4138,4362,4633,4861,5114
TX,0,0,0,0,0,0,0,0,0,0,...,4954,5704,6363,7007,7583,8653,9717,10563,12033,12958
UT,0,0,0,0,0,0,0,0,0,0,...,1076,1244,1422,1605,1675,1739,1848,1979,2103,2206
VA,0,0,0,0,0,0,0,0,0,0,...,1702,2009,2407,2635,2876,3333,3645,4042,4506,5077
VT,0,0,0,0,0,0,0,0,0,0,...,338,389,461,512,543,575,605,628,679,711
WA,1,1,1,1,1,1,1,1,1,1,...,6818,7119,7655,8017,8383,8681,9096,9606,9884,10224
WI,0,0,0,0,0,0,0,0,0,0,...,1730,1916,2112,2266,2438,2578,2756,2885,3068,3213
WV,0,0,0,0,0,0,0,0,0,0,...,217,237,281,320,345,412,479,520,573,591
WY,0,0,0,0,0,0,0,0,0,0,...,153,166,187,199,212,221,230,239,252,261

In [4]:
# transposing state data
states_cases = casesByState.transpose() # 81 rows (days)
states_cases_Mar1 = states_cases.loc['3/10/2020':,] # 33 rows (days)

In [ ]:
statePlot = states_cases_Mar1.plot(kind = 'line')
statePlot.legend(loc = 'bottom')
statePlot.show()